<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ruangan extends Login_Controller
{
    function __construct(){
        parent::__construct();
        $this->load->model('Ruangan_model');
        $this->load->library('form_validation');
    }

    //MASTER DATA
    public function master(){
		$level 				= $this->session->userdata('level');
		$idPegawai			= $this->session->userdata('idpengguna');
		$data['level']		= $level;
		$data['idPegawai']	= $idPegawai;
		
        $ruangan = $this->Ruangan_model->get_all();
		$data = array(
            'ruangan_data' => $ruangan,
            'view' =>'eksekutor/booking/ruangan_list'
        );

        $this->load->view('template', $data);
    }
	
    public function index(){
		$this->status_eksekutor();
    }

    public function status_eksekutor(){
        $ruangan = $this->Ruangan_model->get_daftarForward();

        $data = array(
            'ruangan_data' => $ruangan,
            'view' => 'eksekutor/booking/status_eksekutor'
        );
        
        $this->load->view('template', $data);
    }

    public function detail_sts_eksekutor($id_request){
		$ideksekutor		= $this->session->userdata('idpengguna');

		$this->_baca_booking($id_request, $ideksekutor);
				
        $ruangan     = $this->Ruangan_model->get_by_idrequest($id_request);		
        /*
		$qforward	= $this->db->query("select 
											eksekutor.unit, request_ruangan_forward.sts_eksekusi 
											from eksekutor, request_ruangan_forward
											where eksekutor.idpengguna=request_ruangan_forward.ideksekutor 
											order by request_ruangan_forward.sts_eksekusi asc")->result();
		*/
		$info       = $this->Ruangan_model->get_reqLimit($id_request);

        $data = array(
            'info'          => $info,
            'ruangan_data'  => $ruangan,
            'id_request'  	=> $id_request,
            //'qforward'   	=> $qforward,
			'ideksekutor'	=> $ideksekutor,
            'action'        => 'eksekutor/ruangan/sts_eksekutor_action/'.$id_request,
            'view'          => 'eksekutor/booking/detail_status_eksekutor'
        );
        
        $this->load->view('template', $data);
    }
    function _baca_booking($id_request, $ideksekutor){
        $data = array(
            'baca_eksekutor' =>1
        );
        $this->Ruangan_model->baca_booking($id_request, $ideksekutor, $data);
    }
	  	
    public function sts_eksekutor_action($id_request){
		$sts_eksekusi		= $this->input->post('sts_eksekusi', TRUE);
		$ideksekutor		= $this->session->userdata('idpengguna');

        $photo              = $_FILES['photo']['tmp_name'];
        $nama_photo         = $_FILES['photo']['name'];
        $nmphoto            = '';
 
        if($nama_photo != ''){
            $tipe               = $_FILES['photo_lokasi']['type'];
            $extensi            = explode('.',$nama_photo);  
            $extension          = $extensi[1];               
            if(($extension=="jpg")||($extension=="png")){               
            $nmphoto = 'RF'.time().'.'.$extension;
                copy($photo, "assets/dist/img/kesiapan_eksekutor/".$nmphoto);        
            }else{
                redirect(site_url('eksekutor/ruangan/detail_sts_eksekutor/'.$id_request.'/extension'));
            }
        }


        $data = array(
            'sts_eksekusi' =>$sts_eksekusi,    
            'foto'         =>$nmphoto    
        );

		//update tabel request_ruangan ubah status sts_eksekusi
		$this->Ruangan_model->update_ruangan_forward($id_request, $ideksekutor, $data);
		redirect(site_url('eksekutor/ruangan/detail_sts_eksekutor/'.$id_request.'/success/update-status-eksekutor'));
    }    

}

/* End of file Ruangan.php */
/* Location: ./application/controllers/eksekutor/Ruangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-13 18:39:50 */
/* http://harviacode.com */