<?php if (!defined('BASEPATH'))exit('No direct script access allowed');

class Feedback extends Login_Controller
{
    function __construct(){
        parent::__construct();
        $this->load->model('Feedback_model');
		$this->load->model('login_model');
        $this->load->library('form_validation');
    }

    public function index(){
		$this->form();
	}

    public function form(){
		$level 				= $this->session->userdata('level');
		$idPegawai			= $this->session->userdata('idpengguna');
		$data['level']		= $level;
		$data['idPegawai']	= $idPegawai;
		
        //$ruangan = $this->Barang_model->get_all();
		$data = array(
			'cek_data' 		=> $this->Feedback_model->getAllPeg($idPegawai)->num_rows(), 
			'feedback_data' => $this->Feedback_model->getAllPeg($idPegawai)->result(), 
            'action' 		=> site_url('pegawai/feedback/feedback_action'),			
            'view' 	 		=> 'pegawai/feedback/feedback_form'
        );

        $this->load->view('template', $data);
    }

    public function feedback_action(){
		$level 				= $this->session->userdata('level');
		$idpengguna			= $this->session->userdata('idpengguna');
	
		date_default_timezone_set('Asia/Jakarta');
		$wkt = date('Y-m-d H:i:s');
		
		$id_request = date('YmdHis');
		$data = array(
			 	 	 	 		
			'idfeedback'		=> $id_request,
			'idpengguna' 		=> $idpengguna,
			'feedback' 			=> $this->keamanan->post($this->input->post('feedback', TRUE)),
			'wkt' 				=> $wkt,
			'baca_admin' 		=> '0000-00-00 00:00:00'
		);
		$this->Feedback_model->insert($data);
        redirect(site_url('pegawai/feedback/form/message_send'));	
	}

}

/* End of file feedback.php */
/* Location: ./application/controllers/pegawai/feddback.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-25 15:55:34 */
/* http://harviacode.com */