<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Feedback_model extends CI_Model{

    public $order = 'DESC';
	public $table_feedback = 'feedback';
    function __construct(){
        parent::__construct();
    }
    // insert data
    function insert($data){
        $this->db->insert($this->table_feedback, $data);
    }

    function getAllPeg($idPegawai){
        $this->db->where('idpengguna', $idPegawai);
        return $this->db->get($this->table_feedback);
    }

    function getAll(){
        $this->db->order_by('wkt', 'DESC');
        return $this->db->get($this->table_feedback);
    }
	
    function get_by_id($id){
        $this->db->where($this->idfeedback, $id);
        return $this->db->get($this->table_feedback)->row();
    }

    // delete data
    function delete($id){
        $this->db->where($this->idfeedback, $id);
        $this->db->delete($this->table_feedback);
    }

    function detail_tanggal($idfeedback){
        $sql = "SELECT DATE(wkt) AS tgl FROM feedback where idfeedback = ?"; 
        return $this->db->query($sql, $idfeedback)->row_array();
    }
    function detail_jam($idfeedback){
        $sql = "SELECT DATE_FORMAT(wkt, '%H:%i:%s') AS jam FROM feedback where idfeedback = ?";  
        return $this->db->query($sql, $idfeedback)->row_array();
    }
    //baca request perbaikan admin
    function baca($id_request, $data){
        $this->db->where('id_request', $id_request);
        $this->db->update('request_barang', $data);
    }
  
}

/* End of file Barang_model.php */
/* Location: ./application/models/Eksekutor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-13 06:16:54 */
/* http://harviacode.com */