<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lokasi_model extends CI_Model{

    public $table = 'lokasi';
    public $id = 'kode_lokasi';


    public $order = 'DESC';

    function __construct(){
        parent::__construct();
    }

	function cekLastId(){
		$sql = "SELECT right(kode_lokasi, 5) AS maxs FROM lokasi order by kode_lokasi desc limit 0, 1";
		return $this->db->query($sql)->row();
	}
    // get all
    function get_all(){
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id){
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data){
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    // delete data
    function delete($id){
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Eksekutor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-13 06:16:54 */
/* http://harviacode.com */