<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Feedback extends Login_Controller
{
    function __construct(){
        parent::__construct();
        $this->load->model('Feedback_model');
        $this->load->library('form_validation');
    }

    public function index(){
        $data = array(
			'cek_data' 		=> $this->Feedback_model->getAll()->num_rows(), 
			'feedback_data' => $this->Feedback_model->getAll()->result(), 
            'view' => 'admin/feedback/feedback_list'
        );		
        $this->load->view('template', $data);
    }

}

/* End of file feedback.php */
/* Location: ./application/controllers/admin/feedback.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-13 18:39:50 */
/* http://harviacode.com */