<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class lokasi extends Login_Controller
{
    function __construct(){
        parent::__construct();
        $this->load->model('Lokasi_model');
        $this->load->library('form_validation');
    }

    public function index(){
        $lokasi = $this->Lokasi_model->get_all();

        $data = array(
            'lokasi_data' => $lokasi,
            'view' => 'lokasi/lokasi_list'
        );
		
        $this->load->view('template', $data);
    }


    public function create(){
		
		$lastID	= $this->Lokasi_model->cekLastId();
		$urut = (empty($lastID->maxs) ? 1 : $lastID->maxs += 1);
		$newId = 'L'.sprintf("%05s", $urut);

		$data = array(
			'view' 			=> 'lokasi/lokasi_form',
			'title' 		=> '<i class="fa fa-plus-square"></i> Tambah Data lokasi',
			'action' 		=> site_url('admin/lokasi/create_action'),
			'kode_lokasi' 	=> $newId,
			'lokasi' 		=> set_value('lokasi'),
		);
        $this->load->view('template', $data);
    }
    
    public function create_action(){
		
		$lastID	= $this->Lokasi_model->cekLastId();
		$urut = (empty($lastID->maxs) ? 1 : $lastID->maxs += 1);
		$newId = 'L'.sprintf("%05s", $urut);
		
		$data = array(
			'kode_lokasi'	=> $newId,
			'lokasi'	=> $this->input->post('lokasi',TRUE),
		);

		$this->Lokasi_model->insert($data);
		redirect(site_url('admin/lokasi/index/insert'));
			
    }
    
    public function update($id){
        $row = $this->Lokasi_model->get_by_id($id);
        
		if($row){
			$data = array(
				'title' 		=> '<i class="fa fa-edit"></i> Update lokasi',
				'view' 			=> 'lokasi/lokasi_form',
				'action' 		=> site_url('admin/lokasi/update_action'),
				'kode_lokasi' 	=> set_value('kode_lokasi', $row->kode_lokasi),
				'lokasi' 	=> set_value('lokasi', $row->lokasi),
			);
			$this->load->view('template', $data);
        }else{
            redirect(site_url('admin/lokasi'));
        }
    }
    
    public function update_action(){
		
		$kode_lokasi			= $this->input->post('kode_lokasi', TRUE);
		
		$data = array(
			'lokasi'	=> $this->input->post('lokasi',TRUE),
		);
		$this->Lokasi_model->update($kode_lokasi, $data);
		redirect(site_url('admin/lokasi/update/'.$kode_lokasi.'/success'));
    }
    
    public function delete($id){
        $row = $this->Lokasi_model->get_by_id($id);
        if($row){
            $this->Lokasi_model->delete($id);
			redirect(site_url('admin/lokasi/index/delete'));
        }else{
            redirect(site_url('admin/lokasi'));
        }
    }


    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=lokasi.doc");

        $data = array(
            'pegawai_data' => $this->Lokasi_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('barang/lokasi_doc',$data);
    }

}

/* End of file Barang.php */
/* Location: ./application/controllers/admin/Barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-13 18:39:50 */
/* http://harviacode.com */